<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ahorro.Exports</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="QuestPDF" Version="2024.12.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ahorro.Data\Ahorro.Data.csproj" />
    <ProjectReference Include="..\Ahorro.Models\Ahorro.Models.csproj" />
    <ProjectReference Include="..\Ahorro.Helpers\Ahorro.Helpers.csproj" />
    <ProjectReference Include="..\Ahorro.Services\Ahorro.Services.csproj" />
  </ItemGroup>
</Project>
