<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Ahorro.Charts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ahorro.Themes\Ahorro.Themes.csproj" />
  </ItemGroup>
</Project>
