<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Ahorro.Views</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ahorro.ViewModels\Ahorro.ViewModels.csproj" />
    <ProjectReference Include="..\Ahorro.Themes\Ahorro.Themes.csproj" />
    <ProjectReference Include="..\Ahorro.Charts\Ahorro.Charts.csproj" />
  </ItemGroup>
</Project>
